sample:
    my_sample
work_folder:
    my_sample
fastq:
    R1: A.fq
    R2: B.fq

# afefef
software:
    mapper: bwa
    samtools: samtools
    gatk: gatk
    

#
support: 
    reference: hg38.fasta
    index: /database/hg38/hg38
    known_sites_snp: dbsnp_138.b37.vcf
    known_sites_indel: Mills_and_1000G_gold_standard.indels.b37.vcf